INSERT INTO SAMPLETAW.USUARIO (NOMBRE, APELLIDOS, DOMICILIO, CIUDAD_RESIDENCIA, PASSWORD, USERNAME, SEXO, FECHA_CREACION) 
	VALUES ('Merlinsito', 'Sieringsito', 'Rincon de la V.', 'Malaga', '123', 'Danix5', 'Masculino', CURRENT_DATE);

INSERT INTO SAMPLETAW.ANALISTA (USUARIO_ID) 
	VALUES (1);

INSERT INTO SAMPLETAW.ANALISIS (DESCRIPCION, ANALISTA_USUARIO_ID) 
	VALUES ('Sexo y Ciudades de todos los usuarios en el 2021', 1);

INSERT INTO SAMPLETAW.TIPOANALISIS (NOMBRE, ANALISIS_ID) 
	VALUES ('Sexo', 1);
INSERT INTO SAMPLETAW.TIPOANALISIS (NOMBRE, ANALISIS_ID) 
	VALUES ('Ciudad', 1);

INSERT INTO SAMPLETAW.CAMPOANALISIS (NOMBRE, VALOR, TIPOANALISIS_ID) 
	VALUES ('Masculino', 20, 1);
INSERT INTO SAMPLETAW.CAMPOANALISIS (NOMBRE, VALOR, TIPOANALISIS_ID) 
	VALUES ('Femenino', 22, 1);
INSERT INTO SAMPLETAW.CAMPOANALISIS (NOMBRE, VALOR, TIPOANALISIS_ID) 
	VALUES ('Malaga', 50, 2);
INSERT INTO SAMPLETAW.CAMPOANALISIS (NOMBRE, VALOR, TIPOANALISIS_ID) 
	VALUES ('Barcelona', 90, 2);
INSERT INTO SAMPLETAW.CAMPOANALISIS (NOMBRE, VALOR, TIPOANALISIS_ID) 
	VALUES ('Madrid', 92, 2);

--ALTER TABLE TIPOANALISIS ALTER COLUMN id RESTART WITH 1